-- ==========================================================
-- PHASE V: TABLE CREATION
-- ==========================================================
CREATE TABLE USERS (
    User_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_name   VARCHAR2(50),
    Role        VARCHAR2(20) CHECK (Role IN ('ADMIN', 'CUSTOMER', 'EMPLOYEE')),
    Password    VARCHAR2(50)
);

CREATE TABLE PRODUCTS (
    Product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product_name VARCHAR2(100),
    Category     VARCHAR2(50),
    Price        NUMBER(10, 2),
    Stock_qty    NUMBER CHECK (Stock_qty >= 0)
);

CREATE TABLE CART (
    Cart_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_id      NUMBER REFERENCES USERS(User_id),
    Product_id   NUMBER REFERENCES PRODUCTS(Product_id),
    Quantity     NUMBER
);

CREATE TABLE ORDERS (
    Order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_id      NUMBER REFERENCES USERS(User_id),
    Total_amt    NUMBER(10, 2),
    Order_date   DATE DEFAULT SYSDATE,
    Status       VARCHAR2(20)
);

CREATE TABLE ORDER_DETAILS (
    Detail_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Order_id     NUMBER REFERENCES ORDERS(Order_id),
    Product_id   NUMBER REFERENCES PRODUCTS(Product_id),
    Quantity     NUMBER,
    Unit_Price   NUMBER(10, 2)
);

CREATE TABLE PAYMENTS (
    Payment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Order_id     NUMBER REFERENCES ORDERS(Order_id),
    Amount       NUMBER(10, 2),
    Pay_Method   VARCHAR2(20)
);

CREATE TABLE STOCK_LOGS (
    Log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product_id   NUMBER REFERENCES PRODUCTS(Product_id),
    Old_qty      NUMBER,
    New_qty      NUMBER,
    Action_type  VARCHAR2(20),
    Update_date  DATE DEFAULT SYSDATE
);

CREATE TABLE SYSTEM_AUDIT_LOG (
    Audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_name    VARCHAR2(50),
    Message      VARCHAR2(200),
    Action_Type  VARCHAR2(50),
    Log_Date     DATE DEFAULT SYSDATE
);

CREATE TABLE HOLIDAYS (
    Holiday_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Holiday_date DATE UNIQUE,
    Description  VARCHAR2(100)
);

-- ==========================================================
-- PHASE V: DATA INSERTION
-- ==========================================================
BEGIN
    -- Users
    INSERT INTO USERS (User_name, Role, Password) VALUES ('Manzi_Admin', 'ADMIN', 'admin123');
    INSERT INTO USERS (User_name, Role, Password) VALUES ('Ephrem_Staff', 'EMPLOYEE', 'staff123');
    INSERT INTO USERS (User_name, Role, Password) VALUES ('John_Doe', 'CUSTOMER', 'pass1');
    INSERT INTO USERS (User_name, Role, Password) VALUES ('Sarah_Mutesi', 'CUSTOMER', 'pass2');
    
    FOR i IN 1..30 LOOP
        INSERT INTO USERS (User_name, Role, Password) VALUES ('Customer_'||i, 'CUSTOMER', 'pass'||i);
    END LOOP;

    -- Products
    INSERT INTO PRODUCTS (Product_name, Category, Price, Stock_qty) VALUES ('HP Laptop', 'Electronics', 450000, 10);
    INSERT INTO PRODUCTS (Product_name, Category, Price, Stock_qty) VALUES ('Samsung Phone', 'Electronics', 850000, 5);
    INSERT INTO PRODUCTS (Product_name, Category, Price, Stock_qty) VALUES ('Milk 1L', 'Groceries', 1200, 100);
    INSERT INTO PRODUCTS (Product_name, Category, Price, Stock_qty) VALUES ('Bread', 'Groceries', 1000, 50);
    INSERT INTO PRODUCTS (Product_name, Category, Price, Stock_qty) VALUES ('Rice 1kg', 'Groceries', 1500, 200);

    -- Holidays
    INSERT INTO HOLIDAYS (Holiday_date, Description) VALUES (TO_DATE('2025-12-25', 'YYYY-MM-DD'), 'Christmas Day');
    INSERT INTO HOLIDAYS (Holiday_date, Description) VALUES (TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'New Year');

    COMMIT;
END;
/

-- ==========================================================
-- PHASE VI: PACKAGE WITH WINDOW FUNCTIONS
-- ==========================================================
CREATE OR REPLACE PACKAGE PKG_SHOPPING AS
    g_current_user_id NUMBER;

    -- Standard Procedures
    PROCEDURE set_user(p_user_id NUMBER);
    FUNCTION fn_get_stock(p_prod_id NUMBER) RETURN NUMBER;
    FUNCTION fn_get_cart_total(p_user_id NUMBER) RETURN NUMBER;
    FUNCTION fn_get_product_price(p_prod_id NUMBER) RETURN NUMBER;
    PROCEDURE add_to_cart(p_user_id NUMBER, p_prod_id NUMBER, p_qty NUMBER);
    PROCEDURE checkout(p_user_id NUMBER);
    
    -- NEW: Analytics Procedure using Window Functions
    PROCEDURE generate_analytics;
END PKG_SHOPPING;
/

CREATE OR REPLACE PACKAGE BODY PKG_SHOPPING AS

    -- 1. PROCEDURE: Set User
    PROCEDURE set_user(p_user_id NUMBER) IS
    BEGIN
        g_current_user_id := p_user_id;
        DBMS_OUTPUT.PUT_LINE('User set to ID: ' || p_user_id);
    END set_user;

    -- 2. FUNCTION: Get Stock Level
    FUNCTION fn_get_stock(p_prod_id NUMBER) RETURN NUMBER IS
        v_qty NUMBER;
    BEGIN
        SELECT Stock_qty INTO v_qty FROM PRODUCTS WHERE Product_id = p_prod_id;
        RETURN v_qty;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 0;
    END fn_get_stock;

    -- 3. FUNCTION: Calculate Cart Total
    FUNCTION fn_get_cart_total(p_user_id NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT SUM(c.Quantity * p.Price) INTO v_total
        FROM CART c JOIN PRODUCTS p ON c.Product_id = p.Product_id
        WHERE c.User_id = p_user_id;
        RETURN NVL(v_total, 0);
    END fn_get_cart_total;

    -- 4. FUNCTION: Get Product Price
    FUNCTION fn_get_product_price(p_prod_id NUMBER) RETURN NUMBER IS
        v_price NUMBER;
    BEGIN
        SELECT Price INTO v_price FROM PRODUCTS WHERE Product_id = p_prod_id;
        RETURN v_price;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 0;
    END fn_get_product_price;

    -- 5. PROCEDURE: Add to Cart
    PROCEDURE add_to_cart(p_user_id NUMBER, p_prod_id NUMBER, p_qty NUMBER) IS
        v_stock NUMBER;
        v_count NUMBER;
    BEGIN
        v_stock := fn_get_stock(p_prod_id);
        IF v_stock < p_qty THEN
            RAISE_APPLICATION_ERROR(-20001, 'Error: Not enough stock.');
        END IF;

        SELECT COUNT(*) INTO v_count FROM CART 
        WHERE User_id = p_user_id AND Product_id = p_prod_id;

        IF v_count > 0 THEN
            UPDATE CART SET Quantity = Quantity + p_qty
            WHERE User_id = p_user_id AND Product_id = p_prod_id;
        ELSE
            INSERT INTO CART (User_id, Product_id, Quantity)
            VALUES (p_user_id, p_prod_id, p_qty);
        END IF;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Item added to cart.');
    END add_to_cart;

    -- 6. PROCEDURE: Checkout
    PROCEDURE checkout(p_user_id NUMBER) IS
        v_total NUMBER;
        v_order_id NUMBER;
        CURSOR my_cart IS SELECT Product_id, Quantity FROM CART WHERE User_id = p_user_id;
        v_pid NUMBER; v_qty NUMBER; v_price NUMBER;
    BEGIN
        v_total := fn_get_cart_total(p_user_id);
        IF v_total = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Cart is empty!'); END IF;

        INSERT INTO ORDERS (User_id, Total_amt, Status)
        VALUES (p_user_id, v_total, 'COMPLETED')
        RETURNING Order_id INTO v_order_id;

        OPEN my_cart;
        LOOP
            FETCH my_cart INTO v_pid, v_qty;
            EXIT WHEN my_cart%NOTFOUND;
            
            v_price := fn_get_product_price(v_pid);
            
            INSERT INTO ORDER_DETAILS (Order_id, Product_id, Quantity, Unit_Price)
            VALUES (v_order_id, v_pid, v_qty, v_price);
            
            UPDATE PRODUCTS SET Stock_qty = Stock_qty - v_qty WHERE Product_id = v_pid;
        END LOOP;
        CLOSE my_cart;

        DELETE FROM CART WHERE User_id = p_user_id;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Checkout Success! Order ID: ' || v_order_id);
    END checkout;

    -- =============================================
    -- 7. ANALYTICS (Using RANK and LAG)
    -- =============================================
    PROCEDURE generate_analytics IS
        
        -- Cursor 1: Use RANK() to find top sellers
        CURSOR c_ranks IS
            SELECT p.Product_name, SUM(d.Quantity) as Total_Sold,
                   RANK() OVER (ORDER BY SUM(d.Quantity) DESC) as Rank_Num
            FROM PRODUCTS p
            JOIN ORDER_DETAILS d ON p.Product_id = d.Product_id
            GROUP BY p.Product_name;

        -- Cursor 2: Use LAG() to compare current order with previous order
        CURSOR c_trends IS
            SELECT Order_id, Order_date, Total_amt,
                   -- LAG looks at the previous row's Total_amt
                   LAG(Total_amt, 1, 0) OVER (ORDER BY Order_date) as Previous_Amt
            FROM ORDERS
            ORDER BY Order_date;

        v_name VARCHAR2(100); v_sold NUMBER; v_rank NUMBER;
        v_oid NUMBER; v_date DATE; v_curr NUMBER; v_prev NUMBER;
    BEGIN
        -- REPORT 1: RANKING
        DBMS_OUTPUT.PUT_LINE('--- BI REPORT: PRODUCT RANKINGS (Using RANK) ---');
        OPEN c_ranks;
        LOOP
            FETCH c_ranks INTO v_name, v_sold, v_rank;
            EXIT WHEN c_ranks%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Rank ' || v_rank || ': ' || v_name || ' (Sold: ' || v_sold || ')');
        END LOOP;
        CLOSE c_ranks;
        
        DBMS_OUTPUT.PUT_LINE('-------------------------------------------');

        -- REPORT 2: SALES TRENDS
        DBMS_OUTPUT.PUT_LINE('--- BI REPORT: SALES TRENDS (Using LAG) ---');
        OPEN c_trends;
        LOOP
            FETCH c_trends INTO v_oid, v_date, v_curr, v_prev;
            EXIT WHEN c_trends%NOTFOUND;
            
            IF v_prev = 0 THEN
                DBMS_OUTPUT.PUT_LINE('Order ' || v_oid || ': $' || v_curr || ' (First Order)');
            ELSIF v_curr > v_prev THEN
                DBMS_OUTPUT.PUT_LINE('Order ' || v_oid || ': $' || v_curr || ' (UP from $' || v_prev || ')');
            ELSE
                DBMS_OUTPUT.PUT_LINE('Order ' || v_oid || ': $' || v_curr || ' (DOWN from $' || v_prev || ')');
            END IF;
        END LOOP;
        CLOSE c_trends;

    END generate_analytics;

END PKG_SHOPPING;
/

-- ==========================================================
-- PHASE VII: TRIGGERS (Security & Audit)
-- ==========================================================
-- Stock History Trigger
CREATE OR REPLACE TRIGGER trg_stock_history
AFTER UPDATE OF Stock_qty ON PRODUCTS
FOR EACH ROW
BEGIN
    INSERT INTO STOCK_LOGS (Product_id, Old_qty, New_qty, Action_type)
    VALUES (:OLD.Product_id, :OLD.Stock_qty, :NEW.Stock_qty, 'UPDATE');
END;
/

-- Security Compound Trigger
CREATE OR REPLACE TRIGGER trg_security_check
FOR INSERT OR UPDATE OR DELETE ON PRODUCTS
COMPOUND TRIGGER
    v_role       VARCHAR2(20);
    v_day        VARCHAR2(10);
    v_is_holiday NUMBER;
    v_user_id    NUMBER;

    BEFORE STATEMENT IS
    BEGIN
        v_user_id := PKG_SHOPPING.g_current_user_id;
        IF v_user_id IS NOT NULL THEN
            SELECT Role INTO v_role FROM USERS WHERE User_id = v_user_id;
            
            IF v_role = 'EMPLOYEE' THEN
                SELECT TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') INTO v_day FROM DUAL;
                IF v_day IN ('MON', 'TUE', 'WED', 'THU', 'FRI') THEN
                    INSERT INTO SYSTEM_AUDIT_LOG (User_name, Action_Type, Message)
                    VALUES ('User_'||v_user_id, 'BLOCKED', 'Employee on Weekday');
                    RAISE_APPLICATION_ERROR(-20005, 'SECURITY ALERT: Employees cannot work on Weekdays!');
                END IF;

                SELECT COUNT(*) INTO v_is_holiday FROM HOLIDAYS WHERE TRUNC(Holiday_date) = TRUNC(SYSDATE);
                IF v_is_holiday > 0 THEN
                    INSERT INTO SYSTEM_AUDIT_LOG (User_name, Action_Type, Message)
                    VALUES ('User_'||v_user_id, 'BLOCKED', 'Employee on Holiday');
                    RAISE_APPLICATION_ERROR(-20006, 'SECURITY ALERT: Employees cannot work on Holidays!');
                END IF;
            END IF;
        END IF;
    END BEFORE STATEMENT;
END trg_security_check;
/

DBMS_OUTPUT.PUT_LINE('=== FULL PROJECT SETUP COMPLETE ===');

-- Testing our Package
SET SERVEROUTPUT ON;
EXEC PKG_SHOPPING.generate_analytics;

-- Product Ranking (Using DENSE_RANK)
SELECT 
    p.Product_name,
    p.Category,
    SUM(d.Quantity) as Total_Units_Sold,
    -- DENSE_RANK assigns a rank (1, 2, 3) without skipping numbers for ties
    DENSE_RANK() OVER (ORDER BY SUM(d.Quantity) DESC) as Sales_Rank
FROM ORDER_DETAILS d
JOIN PRODUCTS p ON d.Product_id = p.Product_id
GROUP BY p.Product_name, p.Category
ORDER BY Sales_Rank;

-- Sales Trends Analysis (Using LAG)
SELECT 
    Order_id,
    Order_date,
    Total_amt as Current_Sale,
    -- LAG looks at the previous row's value
    LAG(Total_amt, 1, 0) OVER (ORDER BY Order_date) as Previous_Sale,
    -- Calculate the difference
    (Total_amt - LAG(Total_amt, 1, 0) OVER (ORDER BY Order_date)) as Difference
FROM ORDERS
ORDER BY Order_date;

-- Cumulative Revenue (Using SUM OVER)
SELECT 
    Order_id,
    Order_date,
    Total_amt as Daily_Revenue,
    -- Calculates a running total line-by-line
    SUM(Total_amt) OVER (ORDER BY Order_date) as Cumulative_Revenue
FROM ORDERS;


